version: '3'
services:
  db:
    container_name: db
    image: mariadb:10.2.37-bionic
    hostname: db
    networks:
      your-site-net:
    environment:
      - MYSQL_ROOT_PASSWORD=notsecure112
    volumes:
      - $PWD/db/data:/var/lib/mysql
      - $PWD/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  nginx-php:
    container_name: nginx-php
    hostname: nginx-php
    build: nginx
    ports:
      - "80:80"
    networks:
      your-site-net:
    volumes:
      - $PWD/nginx/etc/nginx/conf.d/your-site.conf:/etc/nginx/conf.d/your-site.conf
      - $PWD/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/www-root/:/www-root/
networks:
  your-site-net: